version: "3.7"
services:
  gophish:
    build:
      # Note build arguments here are for builds using docker-compose (pytest)
      # The CI build workflow uses docker and passes the value from bump_version
      args:
        - VERSION=0.0.7
      context: .
      dockerfile: Dockerfile
    image: gophish
    init: true
    restart: always
    ports:
      - target: 3333
        published: 3333
        protocol: tcp
        mode: host
      - target: 8080
        published: 3380
        protocol: tcp
        mode: host
